{{- /*

  template/_deployment.yaml

  Template deployment
  @author Jordan Yong<jordanyong23@gmail.com>

  This takes two objects in the context
  - top: the top context
  - deployment: the properties of the deployment
*/ -}}

{{- define "common.deployment" -}}
{{- $deploymentDefaults := dict "deployment" .top.Values.common.deploymentDefaults -}}
{{- $deployment := dict "deployment" .deployment -}}
{{- $fullName := include "common.fullname" (dict "top" $.top "extra" .deployment) -}}
{{- with mergeOverwrite $deployment $deploymentDefaults -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" $.top | nindent 4 }}
spec:
  replicas: {{ .deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" $.top | nindent 6 }}
  template:
    metadata:
    {{- with .deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "common.selectorLabels" $.top | nindent 8 }}
        {{- with .deployment.labels }}
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      {{- with .deployment.securityContext }}
      securityContext:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if .deployment.serviceAccount }}
      serviceAccount: {{ .deployment.serviceAccount }}
      {{- end }}
      {{- with .deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- if .deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .deployment.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        {{- range $k, $v := .deployment.containers }}
          {{- include "common.container" (dict "top" $.top "container" $v) | indent 8 }}
        {{- end }}
      {{- if .deployment.initContainers }}
      initContainers:
        {{- range $k, $v := .deployment.initContainers }}
          {{- include "common.init-container" (dict "top" $.top "container" $v) | indent 8 }}
        {{- end }}
      {{- end }}
      {{- with .deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trimSuffix "\n" | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}