{{- /*

  templates/_fullname.yaml

  fullname template

  fullname defines a suitably unique name for a resource by combining
  the release name and the chart name.

  Names should be DNS complient, e.g. a-z, 0-9 plus dot (.) and dash (-), and
  should not exceed 63 characters.

  This template takes 2 parameters:
  - top: the top context
  - extra: extra custom values (optional)

  Parameter definitions:
  - .extra.fullnameOverride: Replaces the computed name with this given name
  - .extra.prefix: Prefix
  - .top.Values.fullnamePrefix: Global prefix
  - .extra.suffix: Suffix
  - .top.Values.fullnameSuffix: Global suffix

  The applied order is: "global prefix + prefix + name + suffix + global suffix"
  Usage: 'name: "{{- template "common.fullname" (dict "top" . "extra" .extra) -}}"'

*/ -}}

{{- define "common.fullname"}}
  {{- $extra := default (.extra) dict "" ""}}
  {{- $globaloverrde := default (include "common.fullname.base" .top) .top.Values.fullnameOverride -}}
  {{- $base := default ($globaloverrde) $extra.nameOverride -}}
  {{- $gpre := default "" .top.Values.fullnamePrefix -}}
  {{- $pre := default "" $extra.prefix -}}
  {{- $suf := default "" $extra.suffix -}}
  {{- $gsuf := default "" .top.Values.fullnameSuffix -}}
  {{- $name := print $gpre $pre $base $suf $gsuf -}}
  {{- $name | lower | trunc 54 | trimSuffix "-" -}}
{{- end -}}

{{- define "common.fullname.base" -}}
  {{- $name := .Chart.Name -}}
  {{- if contains $name .Release.Name -}}
  {{- .Release.Name | trunc 63 | trimSuffix "-" -}}
  {{- else -}}
  {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
  {{- end -}}
{{- end -}}
