{{- /*
  templates/_service.yaml

  Template for service

  This takes two objects in the context:
  - top: the top context
  - service: the properties of the service.
*/ -}}

{{- define "common.service" -}}
{{- $fullName := include "common.fullname" (dict "top" $.top "extra" .service) -}}
apiVersion: v1
kind: Service
metadata:
  {{- with .service.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" $.top | nindent 4 }}
spec:
  type: {{ .service.type }}
  {{- with .service.ports }}
  ports:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" $.top | nindent 4 }}
{{- end -}}