
{{- /*
  templates/_vs.yaml

  Template for virtual service

  This takes two objects in the context:
  - top: the top context
  - vs: the properties of the virtual service.
*/ -}}

{{- define "common.vs" -}}
{{- $fullName := include "common.fullname" (dict "top" $.top "extra" .vs) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" $.top | nindent 4 }}
spec:
  {{- with .vs.hosts }}
  hosts:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- with .vs.gateways }}
  gateways:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- with .vs.http }}
  http:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end -}}